
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/opt/app  # Sync local changes
    environment:
      DATABASE_CLIENT: sqlite  # Use SQLite for simplicity
      NODE_ENV: development
    ports:
      - "1337:1337"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/opt/app  # Sync local changes
    environment:
      NEXT_PUBLIC_API_URL: http://backend:1337  # Point to the Strapi backend
    ports:
      - "3000:3000"
