
services:
  backend:
    container_name: strapi
    build:
      context: ./backend  # Path to the backend (Strapi) directory
      dockerfile: Dockerfile
    image: strapi:latest
    restart: unless-stopped
    env_file: ./backend/.env  # Ensure this path is correct
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./backend/config:/opt/app/config
      - ./backend/src:/opt/app/src
      - ./backend/package.json:/opt/package.json
      - ./backend/package-lock.json:/opt/package-lock.json  # Use package-lock.json for npm
      - ./backend/.env:/opt/app/.env
      - ./backend/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64  # for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./backend/.env  # Ensure this path is correct
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - strapi

  frontend:
    container_name: next
    build:
      context: ./frontend  # Path to the frontend (Next.js) directory
      dockerfile: Dockerfile
    image: next:latest
    restart: unless-stopped
    env_file: ./frontend/.env.local  # Ensure this path is correct
    environment:
      NEXT_PUBLIC_API_URL: http://backend:1337  # API URL for Next.js to communicate with Strapi
    volumes:
      - ./frontend:/app  # Mount the Next.js application code
    ports:
      - "3000:3000"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: strapi
    driver: bridge
